### ISSUE TITLE
Crashes when used within gamescope

### ISSUE THREAD

**Issue by njdom24** [Supreeeme/extest#21]
OS: NixOS (24.05, 24.11. Same issue)
DE: Sway 1.9, 1.10, and standalone `gamescope-session`
Package version: 1.02

Running with `RUST_BACKTRACE=full gamescope -f -e -- env LD_PRELOAD="/nix/store/dh2mr1j099cqa95b9l6hmhs931d0khmm-extest-1.0.2/lib/libextest.so" steam -gamepadui` crashes the moment I try to move the virtual mouse with my gamepad.

Output:
```
thread '<unnamed>' panicked at src/wayland.rs:27:45:
called `Result::unwrap()` on an `Err` value: NoCompositor
stack backtrace:
   0: 0xf7e7e165 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hc1110274ae4e7b07
   1: 0xf7ea85c6 - core::fmt::write::h4e240e96796e5806
   2: 0xf7e761e6 - std::io::Write::write_fmt::h4d93073349bde64f
   3: 0xf7e84a73 - std::panicking::default_hook::{{closure}}::hcf86a3edcfca26ac
   4: 0xf7e846e5 - std::panicking::default_hook::h5ed810eb900e5181
   5: 0xf7e851c3 - std::panicking::rust_panic_with_hook::h4b66b2d33313a69e
   6: 0xf7e7e552 - std::panicking::begin_panic_handler::{{closure}}::h9caf94c662fb37dd
   7: 0xf7e7e389 - std::sys::backtrace::__rust_end_short_backtrace::h2bcec3e30b586d9e
   8: 0xf7e84d47 - rust_begin_unwind
   9: 0xf7e4d98a - core::panicking::panic_fmt::h3503539bdb00a311
  10: 0xf7e4e12d - core::result::unwrap_failed::hd818af259f0b942a
  11: 0xf7e51adf - extest::wayland::get_axes_range::ha3fcbcb3dd43b28d
  12: 0xf7e51f8b - core::ops::function::FnOnce::call_once::h8618b37dbe543136
  13: 0xf7e54517 - once_cell::imp::OnceCell<T>::initialize::{{closure}}::h51d077a6f0dcb17b
  14: 0xf7e554e2 - once_cell::imp::initialize_or_wait::h43d7dbc3b3f94b39
  15: 0xf7e4c3e8 - once_cell::imp::OnceCell<T>::initialize::he76838f23b6561f5
  16: 0xf7e52f6b - XTestFakeRelativeMotionEvent
  17: 0xdcf8ea2f - <unknown>
  18: 0xdcea9e09 - <unknown>
  19: 0xdce519e4 - <unknown>
  20: 0xdce6def2 - <unknown>
  21: 0xe82bb6de - _ZN16SteamThreadTools7CThread22ThreadExceptionWrapperEPv
  22: 0xe82b949e - <unknown>
  23: 0xe82b9d60 - CatchAndWriteMiniDumpExForVoidPtrFn
  24: 0xe82b9da8 - CatchAndWriteMiniDumpForVoidPtrFn
  25: 0xe82be1c2 - _ZN16SteamThreadTools7CThread10ThreadProcEPv
  26: 0xf7a24f27 - start_thread
  27: 0xf7aba8e8 - __GI___clone3
  28:        0x0 - <unknown>
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0: 0xf7e7e165 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hc1110274ae4e7b07
   1: 0xf7ea85c6 - core::fmt::write::h4e240e96796e5806
   2: 0xf7e761e6 - std::io::Write::write_fmt::h4d93073349bde64f
   3: 0xf7e84a73 - std::panicking::default_hook::{{closure}}::hcf86a3edcfca26ac
   4: 0xf7e846e5 - std::panicking::default_hook::h5ed810eb900e5181
   5: 0xf7e851c3 - std::panicking::rust_panic_with_hook::h4b66b2d33313a69e
   6: 0xf7e7e525 - std::panicking::begin_panic_handler::{{closure}}::h9caf94c662fb37dd
   7: 0xf7e7e389 - std::sys::backtrace::__rust_end_short_backtrace::h2bcec3e30b586d9e
   8: 0xf7e84d47 - rust_begin_unwind
   9: 0xf7e4d9df - core::panicking::panic_nounwind_fmt::h9b851e2c9b03e870
  10: 0xf7e4daa6 - core::panicking::panic_nounwind::hec3520e9f5c46d3a
  11: 0xf7e4db92 - core::panicking::panic_cannot_unwind::hed98384f6cfcc4c8
  12: 0xf7e53137 - XTestFakeRelativeMotionEvent
  13: 0xdcf8ea2f - <unknown>
  14: 0xdcea9e09 - <unknown>
  15: 0xdce519e4 - <unknown>
  16: 0xdce6def2 - <unknown>
  17: 0xe82bb6de - _ZN16SteamThreadTools7CThread22ThreadExceptionWrapperEPv
  18: 0xe82b949e - <unknown>
  19: 0xe82b9d60 - CatchAndWriteMiniDumpExForVoidPtrFn
  20: 0xe82b9da8 - CatchAndWriteMiniDumpForVoidPtrFn
  21: 0xe82be1c2 - _ZN16SteamThreadTools7CThread10ThreadProcEPv
  22: 0xf7a24f27 - start_thread
  23: 0xf7aba8e8 - __GI___clone3
  24:        0x0 - <unknown>
thread caused non-unwinding panic. aborting.
```

**Comment by Supreeeme** [comment]
Gamescope fully supports X11 and afaik doesn't support Wayland clients by default - you can't really run extest, and shouldn't need to anyway.

**Comment by njdom24** [comment]
I need extest to get a visible cursor when running gamescope, just as much as I do with Sway. On that note, prepending `steam` with `env WAYLAND_DISPLAY=$WAYLAND_DISPLAY` fixes my issue with extest crashing.

**Comment by njdom24** [comment]
Closing. It looks like my issue is more accurately represented by #11
